### ISSUE TITLE
dev4 test but qsv av1 sharpening

### ISSUE THREAD

**Issue by guraking** [ma3uk/obs-qsv-onevpl#10]
my test Qsv AV1 good Quality

Can you tell me your setting?

![Untitled-1](https://github.com/ma3uk/obs-qsv-onevpl/assets/37140215/5539088c-7387-43f9-ae11-09afaa8d7788)

QSV.oneVPL_1.1.0.0_dev4 AV1

![QSV oneVPL_1 1 0 0_dev4_1](https://github.com/ma3uk/obs-qsv-onevpl/assets/37140215/f205fc40-0cff-4b3c-862a-178ccc59410d)
![QSV oneVPL_1 1 0 0_dev4_2](https://github.com/ma3uk/obs-qsv-onevpl/assets/37140215/7e339dd0-b81a-4909-aab0-6d464d52df1d)
![QSV oneVPL_1 1 0 0_dev4_3](https://github.com/ma3uk/obs-qsv-onevpl/assets/37140215/df55c48c-5348-404e-b5ed-08eb0c7c09db)

QSV AV1

![QSV AV1_1](https://github.com/ma3uk/obs-qsv-onevpl/assets/37140215/84ae6d72-e6ad-49e8-b5af-235328031146)

**Comment by guraking** [comment]
@ma3uk 

thx bro 👍

**Comment by guraking** [comment]
same 
https://www.youtube.com/watch?v=YIH9XE3gH0U

No matter how hard I look at it QSV AV1 Good Quality

Can you check it out in the next version?

**Comment by ma3uk** [comment]
> 

I don't quite understand what the problem is, because you threw off 3 videos shot in different conditions. To make comparisons correctly, record a sample, duration 1-2 minutes, as close as possible to the original, for example, using CQP or ICQ mode with a quality value of 15, and already recoding the recorded sample, perform a comparison. If you share this sample, it will make everything much easier.

**Comment by ma3uk** [comment]
Also, do not compare the quality of the recording and the quality of the broadcast on youtube, because all videos coming to youtube go through the stage of transcoding into VP9 codec.

**Comment by guraking** [comment]
@ma3uk 
ok sry close issu
