### ISSUE TITLE
[Bug] MFX_ERR_NULL_PTR if trying to use "GAME STREAMING" Scenario

### ISSUE THREAD

**Issue by DatCaptainHorse** [ma3uk/obs-qsv-onevpl#12]
Love the plugin, brings out so many tweakable knobs! I hope to see this existing after OBS oneVPL PR gets merged as well as the tunability is actually quite useful 🙂 

Using Intel Arc A380, as 2nd GPU without any display connected.

Choosing "GAME STREAMING" Scenario will cause `[qsv encoder: 'msdk_impl'] NULL pointer in the input or output arguments (MFX_ERR_NULL_PTR)` error when attempting to start encoder session. Might be new option that got added by driver update, but requires special handling in plugin or new SDK version? Just quick assumptions I had.

![kuva1](https://github.com/ma3uk/obs-qsv-onevpl/assets/14197772/17d4f96c-f7c3-43c3-9e09-0e5d0b286849)
![kuva2](https://github.com/ma3uk/obs-qsv-onevpl/assets/14197772/be7e3aee-1e8a-481f-8b44-ed3e491f1ee0)

**Comment by ma3uk** [comment]
Thank you for your Issue. I am aware of this problem, as far as I know, it has been fixed in the latest versions of the driver, so I advise you to update.
If it does not help, then you will have to wait, now work is actively underway to rewrite the plugin. In the developed version, this problem has been fixed. 

You can write to me in Discord (myonezgg) and I will send the latest test build of the plugin being developed

After making changes to the official OBS QSV plugin, work on this plugin will not be stopped, because this plugin is being developed without backward compatibility of Intel GPUs below the 11th generation, which allows you to add the latest functionality and improve the quality of the output video.

**Comment by ma3uk** [comment]
Fixed with driver 4885
