### ISSUE TITLE
The select GPU in the encoding options is gone

### ISSUE THREAD

**Issue by neveta** [ma3uk/obs-qsv-onevpl#25]
In the latest version, the “select GPU” in the encoding options disappeared and could not be encoded with Intel integrated graphics.

**Comment by ma3uk** [comment]
> In the latest version, the “select GPU” in the encoding options disappeared and could not be encoded with Intel integrated graphics.

The GPU selection option has been removed due to the addition of texture encoding support. Unfortunately, OBS does not allow you to get textures for encoding from the GPU on which it was not running. A workaround is to install the desired GPU in the Windows Control Panel for OBS Studio ([https://www.digitalcitizen.life/set-which-video-cards-are-used-apps-games-windows-10/](how do this)). It is also worth noting that GPUs do not support ExtBRC and Enc Tools parameters with the latest drivers, enabling these parameters exposes an internal error that I cannot influence.

**Comment by neveta** [comment]
> > In the latest version, the “select GPU” in the encoding options disappeared and could not be encoded with Intel integrated graphics.
> 
> The GPU selection option has been removed due to the addition of texture encoding support. Unfortunately, OBS does not allow you to get textures for encoding from the GPU on which it was not running. A workaround is to install the desired GPU in the Windows Control Panel for OBS Studio (https://www.digitalcitizen.life/set-which-video-cards-are-used-apps-games-windows-10/). It is also worth noting that GPUs do not support ExtBRC and EncTools parameters with the latest drivers, enabling these parameters exposes an internal error that I cannot influence.

got it！thx！

**Comment by ma3uk** [comment]
@neveta In release 1.2.0.2, a GPU selection option has been added. Please check the functionality on your configuration. In case of errors, please report them in this thread.

**Comment by neveta** [comment]
The new version has no new issues were found. thanks a lot
