### ISSUE TITLE
HyperEncode feature request

### ISSUE THREAD

**Issue by fuchaohan** [ma3uk/obs-qsv-onevpl#4]
Does this plugin support intel iGPU?
I don't know if it's a problem with my settings, but the UHD770 still occupies  full 3D engine

**Comment by ma3uk** [comment]
Hello, please clarify what you mean by 3D engine? The indicator of the integrated graphics card in the task manager when recording/broadcasting? If yes, then everything works as it should, then you are using the coding mode in performance mode, which intel itself has a name (PG). If your load reaches 100%, I assume that you are using the HEVC codec, in PG mode this codec can work without frame loss only in Slow mode. In order to use the Slow and Very slow modes, it is necessary to enable the Lowpower mode parameter in the settings - this will reduce the load on the 3D engine and distribute the load on specialized blocks. But, I warn you, the Lowpower mode can affect the quality of the output image, so compare the results in the JV Slow mode and with the Lowpower Veryslow enabled and make a decision.

**Comment by ma3uk** [comment]
> Does this plugin support intel iGPU? I don't know if it's a problem with my settings, but the UHD770 still occupies full 3D engine

Hello, please clarify what you mean by 3D engine? The indicator of the integrated graphics card in the task manager when recording/broadcasting? If yes, then everything works as it should, then you are using the coding mode in performance mode, which intel itself has a name (PG). If your load reaches 100%, I assume that you are using the HEVC codec, in PG mode this codec can work without frame loss only in Slow mode. In order to use the Slow and Very slow modes, it is necessary to enable the Lowpower mode parameter in the settings - this will reduce the load on the 3D engine and distribute the load on specialized blocks. But, I warn you, the Lowpower mode can affect the quality of the output image, so compare the results in the JV Slow mode and with the Lowpower Veryslow enabled and make a decision.

**Comment by fuchaohan** [comment]
choose QuickSync H.264
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/23447902/6c93e9d4-1a5a-433e-8813-e09958a14931)
if choose QuickSync HEVC
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/23447902/3380deea-7f32-4f44-8d49-946df19b008b)

**Comment by fuchaohan** [comment]
Because translation software was used, there may be wording errors in some content.
To clarify the current situation, I am using A770+13600K.
I want to use the iGPU that comes with the 13600K and use OBS to take care of the recording
I chose to open OBS with UHD770 inside win11 settings
With this recording, the UHD770 is almost always using the 3D engine, not the Video Decode engine, which can cause serious frame loss even if the quality of the recorded video is reduced
UHD770 supports QSV H264 HEVC video encoding
I think this should be a bug
If I use Intel Arc Control to record, the UHD770 can correctly call the Video Decode engine, and the very high bit rate will not lose frames.
But Intel Arc Control has almost no adjustable items, not as many functions as OBS, if I can use OBS to use iGPU correctly, I still want to use OBS.

**Comment by ma3uk** [comment]
> Поскольку использовалось программное обеспечение для перевода, в некотором контенте могут быть ошибки в формулировках. Чтобы прояснить сложившуюся ситуацию, я использую A770+13600K. Я хочу использовать iGPU, который поставляется с 13600K, и использовать OBS, чтобы позаботиться о записи Я решил открыть OBS с UHD770 в настройках win11 При этой записи UHD770 почти всегда использует движок 3D, а не механизм декодирования видео, что может привести к серьезной потере кадров даже при снижении качества записанного видео UHD770 поддерживает кодирование видео QSV H264 HEVC Я думаю, что это должно быть ошибкой Если я использую Intel Arc Control для записи, UHD770 может правильно вызвать механизм декодирования видео, и очень высокая скорость передачи данных не приведет к потере кадров. Но Intel Arc Control почти не имеет настраиваемых элементов, не так много функций, как OBS, если я могу использовать OBS для правильного использования iGPU, я все равно хочу использовать OBS.
Use the Select GPU parameter to select the target GPU, as well as the Lowpower mode parameter to enable an operation mode similar to Intel Arc Control

**Comment by ma3uk** [comment]
@fuchaohan Use the Select GPU parameter to select the target GPU, as well as the Lowpower mode parameter to enable an operation mode similar to Intel Arc Control

**Comment by ma3uk** [comment]
> выберите QuickSync H.264![image](https://user-images.githubusercontent.com/23447902/239717271-6c93e9d4-1a5a-433e-8813-e09958a14931.png), если выберите QuickSync HEVC ![image](https://user-images.githubusercontent.com/23447902/239717310-3380deea-7f32-4f44-8d49-946df19b008b.png)

Send the log file for error analysis and further correction

**Comment by fuchaohan** [comment]
Sorry, I may have misstated.
How can I get OBS to enable Deep Link Technology (oneVPL Deep Link Hyper Encode)
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/23447902/3b3a258b-baf1-4b1e-94f4-fa3eb6b2aaec)

**Comment by ma3uk** [comment]
> Извините, возможно, я неправильно сказал. Как я могу заставить OBS включить технологию Deep Link (oneVPL Deep Link Hyper Encode) ![образ](https://user-images.githubusercontent.com/23447902/239737860-3b3a258b-baf1-4b1e-94f4-fa3eb6b2aaec.png)

Nothing at the moment. I will add your request to add features. But I can warn you right away - HyperEncode has a lot of restrictions on use, it needs a small GOP size ~= 30 in order for it to give at least some advantage, but such a GOP size will significantly affect the quality of the output image.

**Comment by ma3uk** [comment]
@fuchaohan In build 1.1.0.0_dev2, parameters have been added to configure the behavior of HyperEncode, but to activate it, you need to select parameters such as GOP, GOPRefDist and others, in addition, HyperEncode only works in Lowpower mode.
